/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IDataChunk",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDataChunk__factory>;
    getContractFactory(
      name: "IDataChunkCompiler",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDataChunkCompiler__factory>;
    getContractFactory(
      name: "DataChunkCompiler",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DataChunkCompiler__factory>;
    getContractFactory(
      name: "IDataChunk",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDataChunk__factory>;
    getContractFactory(
      name: "IDataChunkCompiler",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDataChunkCompiler__factory>;
    getContractFactory(
      name: "FFlateDataChunk1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FFlateDataChunk1__factory>;
    getContractFactory(
      name: "FFlateDataChunk2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FFlateDataChunk2__factory>;
    getContractFactory(
      name: "OnchainGas",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OnchainGas__factory>;
    getContractFactory(
      name: "ThreeDataChunk1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ThreeDataChunk1__factory>;
    getContractFactory(
      name: "ThreeDataChunk2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ThreeDataChunk2__factory>;
    getContractFactory(
      name: "ThreeDataChunk3",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ThreeDataChunk3__factory>;
    getContractFactory(
      name: "ThreeDataChunk4",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ThreeDataChunk4__factory>;
    getContractFactory(
      name: "ThreeDataChunk5",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ThreeDataChunk5__factory>;
    getContractFactory(
      name: "ThreeDataChunk6",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ThreeDataChunk6__factory>;
    getContractFactory(
      name: "ThreeDataChunk7",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ThreeDataChunk7__factory>;
    getContractFactory(
      name: "ThreeDataChunk8",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ThreeDataChunk8__factory>;
    getContractFactory(
      name: "ThreeDataChunk9",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ThreeDataChunk9__factory>;
    getContractFactory(
      name: "OnchainGasView",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OnchainGasView__factory>;
    getContractFactory(
      name: "ERC721A__IERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721A__IERC721Receiver__factory>;
    getContractFactory(
      name: "ERC721A",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721A__factory>;
    getContractFactory(
      name: "ERC721AQueryable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721AQueryable__factory>;
    getContractFactory(
      name: "IERC721AQueryable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721AQueryable__factory>;
    getContractFactory(
      name: "IERC721A",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721A__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IDataChunk",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDataChunk>;
    getContractAt(
      name: "IDataChunkCompiler",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDataChunkCompiler>;
    getContractAt(
      name: "DataChunkCompiler",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DataChunkCompiler>;
    getContractAt(
      name: "IDataChunk",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDataChunk>;
    getContractAt(
      name: "IDataChunkCompiler",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDataChunkCompiler>;
    getContractAt(
      name: "FFlateDataChunk1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FFlateDataChunk1>;
    getContractAt(
      name: "FFlateDataChunk2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FFlateDataChunk2>;
    getContractAt(
      name: "OnchainGas",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OnchainGas>;
    getContractAt(
      name: "ThreeDataChunk1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ThreeDataChunk1>;
    getContractAt(
      name: "ThreeDataChunk2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ThreeDataChunk2>;
    getContractAt(
      name: "ThreeDataChunk3",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ThreeDataChunk3>;
    getContractAt(
      name: "ThreeDataChunk4",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ThreeDataChunk4>;
    getContractAt(
      name: "ThreeDataChunk5",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ThreeDataChunk5>;
    getContractAt(
      name: "ThreeDataChunk6",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ThreeDataChunk6>;
    getContractAt(
      name: "ThreeDataChunk7",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ThreeDataChunk7>;
    getContractAt(
      name: "ThreeDataChunk8",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ThreeDataChunk8>;
    getContractAt(
      name: "ThreeDataChunk9",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ThreeDataChunk9>;
    getContractAt(
      name: "OnchainGasView",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OnchainGasView>;
    getContractAt(
      name: "ERC721A__IERC721Receiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721A__IERC721Receiver>;
    getContractAt(
      name: "ERC721A",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721A>;
    getContractAt(
      name: "ERC721AQueryable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721AQueryable>;
    getContractAt(
      name: "IERC721AQueryable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721AQueryable>;
    getContractAt(
      name: "IERC721A",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721A>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
