sources:
  - name: fls-sepolia
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/proxy/67995/fls-sepolia/v0.0.6
    transforms: # new 👇
      - prefix:
          value: sepolia_
          includeRootOperations: true
          includeTypes: false
  - name: fls-mainnet
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/67995/fls/v0.0.1

documents:
  - ./src/**/*.graphql
