/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IMetaDataURI,
  IMetaDataURIInterface,
} from "../../contracts/IMetaDataURI";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "seed",
        type: "uint256",
      },
      {
        internalType: "uint24",
        name: "gasPrice",
        type: "uint24",
      },
    ],
    name: "tokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IMetaDataURI__factory {
  static readonly abi = _abi;
  static createInterface(): IMetaDataURIInterface {
    return new utils.Interface(_abi) as IMetaDataURIInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMetaDataURI {
    return new Contract(address, _abi, signerOrProvider) as IMetaDataURI;
  }
}
