/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDataChunk } from "./IDataChunk";
export type { IDataChunkCompiler } from "./IDataChunkCompiler";
