/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IDataChunk,
  IDataChunkInterface,
} from "../../../contracts/Compiler.sol/IDataChunk";

const _abi = [
  {
    inputs: [],
    name: "data",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IDataChunk__factory {
  static readonly abi = _abi;
  static createInterface(): IDataChunkInterface {
    return new utils.Interface(_abi) as IDataChunkInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDataChunk {
    return new Contract(address, _abi, signerOrProvider) as IDataChunk;
  }
}
